[package]
name = "rusty-search-cloud"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Sovereign zero-dependency HTTP JSON remote cloud search provider for rusty_search"

[dependencies]
rusty-search-core = { workspace = true }
rusty_request = { path = "../../../rusty_request" }
rusty_json = { path = "../../../rusty_json" }
rusty_tokio = { path = "../../../rusty_tokio" }
rusty_std = { path = "../../../rusty_std" }
async-trait = { workspace = true }

[dev-dependencies]
