#!/usr/bin/env python3
"""Regenerates src/constants.rs: SHA-2 constants from their FIPS 180-4 definition.

IVs are the first bits of the fractional parts of square roots of primes, round
constants likewise for cube roots. Exact integer roots, no floating point.
usage: gen_constants.py > src/constants.rs
"""


def primes(n):
    out, c = [], 2
    while len(out) < n:
        if all(c % p for p in out):
            out.append(c)
        c += 1
    return out


def iroot(x, k):
    lo, hi = 0, 1 << (x.bit_length() // k + 1)
    while lo < hi:
        mid = (lo + hi + 1) // 2
        lo, hi = (mid, hi) if mid**k <= x else (lo, mid - 1)
    return lo


def frac_root(p, k, bits):
    return iroot(p << (k * bits), k) & ((1 << bits) - 1)


def emit(name, ty, vals, width):
    print(f"pub(crate) const {name}: [{ty}; {len(vals)}] = [")
    for i in range(0, len(vals), 4 if width == 16 else 8):
        row = vals[i : i + (4 if width == 16 else 8)]
        print("    " + ", ".join(f"0x{v:0{width}x}" for v in row) + ",")
    print("];")


P = primes(80)
print("// @generated by scripts/gen_constants.py from FIPS 180-4 section 4.2 and 5.3. Do not edit.")
emit("SHA256_IV", "u32", [frac_root(p, 2, 32) for p in P[:8]], 8)
emit("SHA256_K", "u32", [frac_root(p, 3, 32) for p in P[:64]], 8)
emit("SHA512_IV", "u64", [frac_root(p, 2, 64) for p in P[:8]], 16)
emit("SHA384_IV", "u64", [frac_root(p, 2, 64) for p in P[8:16]], 16)
emit("SHA512_K", "u64", [frac_root(p, 3, 64) for p in P[:80]], 16)
