/** A dozen cards of the real deck, for the in-browser demo and the unit tests (the binary ships all 100). */
import type { Baseline } from './types'

export const DEMO_DECK: Baseline[] = [
  {"id": "00000000-0000-4000-8000-000000000001", "number": 1, "name": "Childcare Helpers (Kids)", "suit": "Home", "conception": "Notice where you will need outside help (sitters, daycare, relatives) before a gap appears.", "planning": "Keep a short roster of vetted helpers with rates, house rules, and a booking routine.", "execution": "Book, brief, pay, and debrief each helper; replace anyone who drops off the roster.", "minimumStandardOfCare": ["Roster has 2+ vetted helpers", "Helper booked 48+ hours ahead or a backup is lined up", "Helper has emergency contacts and house rules before each visit"]},
  {"id": "00000000-0000-4000-8000-000000000002", "number": 2, "name": "Cleaning", "suit": "Home", "conception": "Decide what clean enough means for each room and how often it needs attention.", "planning": "Build a room-by-room rotation, stock supplies, and decide what is DIY versus hired.", "execution": "Do the cleaning on schedule, or book and oversee the cleaner, without being reminded.", "minimumStandardOfCare": ["Bathrooms and kitchen surfaces cleaned weekly", "Floors vacuumed or mopped weekly", "Supplies restocked before they run out"]},
  {"id": "00000000-0000-4000-8000-000000000003", "number": 3, "name": "Dishes", "suit": "Home", "conception": "See dishes piling up and know what needs hand-washing versus the dishwasher.", "planning": "Pick a routine (after each meal or nightly) and keep detergent and sponges stocked.", "execution": "Load, run, unload, and hand-wash; clear the sink before bed.", "minimumStandardOfCare": ["Sink empty before bed", "Dishwasher run and unloaded daily", "Pots and pans washed the same day"]},
  {"id": "00000000-0000-4000-8000-000000000023", "number": 23, "name": "Auto", "suit": "Out", "conception": "Track each vehicle's maintenance, registration, insurance, and safety.", "planning": "Calendar service intervals and renewals, and pick a trusted mechanic.", "execution": "Schedule and deliver for service, renew registration and inspections, and handle repairs and tires.", "minimumStandardOfCare": ["Service done at manufacturer intervals", "Registration and insurance never lapse", "Tires, fluids, and fuel checked before trips"]},
  {"id": "00000000-0000-4000-8000-000000000024", "number": 24, "name": "Birthday Celebrations (Other Kids)", "suit": "Out", "conception": "Know which friends' birthdays are coming and what is expected.", "planning": "Calendar RSVPs, set a gift budget, and pick gifts and cards.", "execution": "RSVP, buy, wrap, and get your child there.", "minimumStandardOfCare": ["RSVP sent on time", "Gift bought and wrapped 2 days ahead", "Card signed by your child"]},
  {"id": "00000000-0000-4000-8000-000000000045", "number": 45, "name": "Bathing & Grooming (Kids)", "suit": "Caregiving", "conception": "Track hygiene needs by age: baths, hair, nails, teeth, skin.", "planning": "Set routines and keep products and tools stocked.", "execution": "Do baths, haircare, nail trims, and grooming.", "minimumStandardOfCare": ["Baths on the agreed schedule", "Nails trimmed regularly", "Products stocked"]},
  {"id": "00000000-0000-4000-8000-000000000046", "number": 46, "name": "Bedtime Routine (Kids)", "suit": "Caregiving", "conception": "Know each child's sleep needs and what makes bedtime work.", "planning": "Set the routine, timing, and rules.", "execution": "Run bath, pajamas, teeth, story, and lights out.", "minimumStandardOfCare": ["In bed by the agreed time", "Same sequence each night", "Screens off before bed"]},
  {"id": "00000000-0000-4000-8000-000000000067", "number": 67, "name": "Adult Friendships (Player 1)", "suit": "Magic", "conception": "Remember that your own friendships matter to your health and your marriage.", "planning": "Plan regular time with friends.", "execution": "Show up for friend time.", "minimumStandardOfCare": ["Regular friend time on the calendar", "Partner covers home duties without penalty"]},
  {"id": "00000000-0000-4000-8000-000000000068", "number": 68, "name": "Adult Friendships (Player 2)", "suit": "Magic", "conception": "Remember that your own friendships matter to your health and your marriage.", "planning": "Plan regular time with friends.", "execution": "Show up for friend time.", "minimumStandardOfCare": ["Regular friend time on the calendar", "Partner covers home duties without penalty"]},
  {"id": "00000000-0000-4000-8000-000000000089", "number": 89, "name": "Aging/Ailing Parent", "suit": "Wild", "conception": "Recognize when a parent needs more support.", "planning": "Gather information, discuss options, share duties with siblings, and plan costs.", "execution": "Coordinate care, appointments, finances, and visits.", "minimumStandardOfCare": ["Care plan written down", "Roles with siblings clear", "Partner informed of the load"]},
  {"id": "00000000-0000-4000-8000-000000000090", "number": 90, "name": "Death", "suit": "Wild", "conception": "Be prepared for the practical and emotional needs after a loss.", "planning": "Plan logistics: notifications, services, legal tasks, and support for kids.", "execution": "Handle arrangements, communication, and follow-through.", "minimumStandardOfCare": ["Key documents located", "Duties shared between partners", "Kids supported"]},
  {"id": "00000000-0000-4000-8000-000000000099", "number": 99, "name": "Unicorn Space (Player 1)", "suit": "Unicorn Space", "conception": "Know what makes you uniquely you beyond your roles.", "planning": "Carve out recurring time and resources for it.", "execution": "Show up for it.", "minimumStandardOfCare": ["Protected recurring time", "No guilt or penalty from partner"]},
]
