#!/usr/bin/env node
/**
 * Checks the JS reverse-trace port against the Rust reference.
 *
 * `src/scenarios/acquisition_status.json` and
 * `src/scenarios/acquisition_status.reports.json` are both generated by
 * the Rust crate:
 *
 *   cargo run -p rusty-meshed-trace --example export > export.json
 *   # scenario -> acquisition_status.json, reports -> acquisition_status.reports.json
 *
 * This script re-traces the scenario with `src/reverseTrace.js` and fails
 * if any report differs from what the crate produced. Run via `npm test`.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { traceAll } from "../src/reverseTrace.js";

const here = dirname(fileURLToPath(import.meta.url));
const scenario = JSON.parse(readFileSync(join(here, "../src/scenarios/acquisition_status.json"), "utf8"));
const expected = JSON.parse(readFileSync(join(here, "../src/scenarios/acquisition_status.reports.json"), "utf8"));

// Compare with a canonical key order and f32-tolerant fractions.
function canon(v) {
  if (Array.isArray(v)) return v.map(canon);
  if (v && typeof v === "object") {
    return Object.fromEntries(Object.keys(v).sort().map((k) => [k, k === "fraction" ? Math.fround(v[k]) : canon(v[k])]));
  }
  return v;
}

const actual = traceAll(scenario);
let failures = 0;
expected.forEach((exp, i) => {
  const a = JSON.stringify(canon(actual[i])), e = JSON.stringify(canon(exp));
  if (a !== e) {
    failures++;
    console.error(`MISMATCH for outcome ${exp.outcome}\n  rust: ${e}\n  js:   ${a}`);
  } else {
    console.log(`ok  ${exp.outcome} → ${exp.achievable.kind}${exp.achievable.fraction != null ? ` (${Math.round(exp.achievable.fraction * 100)}%)` : ""}`);
  }
});
if (actual.length !== expected.length) {
  failures++;
  console.error(`outcome count differs: rust ${expected.length}, js ${actual.length}`);
}
if (failures) { console.error(`${failures} mismatch(es)`); process.exit(1); }
console.log(`trace parity: ${expected.length} outcomes match the Rust reference`);
