#!/usr/bin/env python3
"""Generate ADR-0003's workspace map from cargo metadata, or verify its bytes.

Usage: generate_workspace_map.py METADATA [--verify PATH]
The checked-in map replaces hand-maintained crate relationship prose.
"""
import argparse
import json
import sys
from pathlib import Path

from check_workspace_layers import (
    LAYER_ORDER,
    package_family,
    package_layer,
    workspace_edges,
    workspace_packages,
)


def markdown_cell(value: str) -> str:
    """Keep text on one table line and escape Markdown/HTML delimiters."""
    return " ".join(value.split()).replace("&", "&amp;").replace("<", "&lt;").replace(
        ">", "&gt;"
    ).replace("\\", "\\\\").replace("|", "\\|").replace("`", "\\`")


def generate_workspace_map(metadata: dict) -> str:
    """Render deterministic rows with unique other-member dependent counts."""
    packages = workspace_packages(metadata)
    dependents = {pkg_id: set() for pkg_id in packages}
    for caller, target in workspace_edges(metadata):
        if caller != target:
            dependents[target].add(caller)
    rows = []
    for pkg_id, pkg in packages.items():
        layer = package_layer(pkg)
        if layer not in LAYER_ORDER:
            raise ValueError(f"{pkg['name']}: missing or unrecognized rusty_mill.layer")
        family = package_family(pkg, metadata["workspace_root"])
        rows.append((LAYER_ORDER.index(layer), family, pkg["name"],
                     pkg.get("description") or "", len(dependents[pkg_id])))
    lines = [
        "# Workspace map",
        "",
        "Generated by `.github/scripts/generate_workspace_map.py`; do not edit by hand.",
        "",
        "Regenerate from the workspace root:",
        "",
        "```sh",
        "cargo metadata --format-version=1 --all-features --locked > /tmp/metadata.json",
        "python3 .github/scripts/generate_workspace_map.py /tmp/metadata.json > docs/WORKSPACE-MAP.md",
        "```",
        "",
        "Dependents count distinct other workspace members with a dependency of any kind.",
        "Families are the current directories immediately below `crates/`.",
        "",
        "| Layer | Family | Crate name | Description | Dependents count |",
        "| --- | --- | --- | --- | ---: |",
    ]
    for rank, family, name, description, count in sorted(rows):
        cells = (LAYER_ORDER[rank], family, name, description, str(count))
        lines.append("| " + " | ".join(markdown_cell(cell) for cell in cells) + " |")
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write UTF-8 Markdown, or fail silently except for a stale-file message."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("metadata", type=Path)
    parser.add_argument("--verify", type=Path)
    args = parser.parse_args()
    metadata = json.loads(args.metadata.read_text(encoding="utf-8"))
    generated = generate_workspace_map(metadata).encode("utf-8")
    if args.verify is None:
        sys.stdout.buffer.write(generated)
        return
    try:
        current = args.verify.read_bytes()
    except FileNotFoundError:
        current = None
    if current != generated:
        print(
            f"{args.verify} is stale — regenerate with "
            "python3 .github/scripts/generate_workspace_map.py "
            f"{args.metadata} > {args.verify}",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
