[package]
name = "remind_me_mcp"
version = "0.3.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Rusty-Mill/rusty_mill"

[package.metadata.rusty_mill]
layer = "apps"

[dependencies]
remind_me_core.workspace = true

serde = { workspace = true }
serde_json = "1.0"
async-trait = { workspace = true }
thiserror = "2.0"
tokio = { version = "1.0", features = ["full"] }
