"""initial schema

Revision ID: 4436ffaad795
Revises: 
Create Date: 2026-06-16 15:54:42.837738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4436ffaad795'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owns_book', sa.Boolean(), nullable=False),
    sa.Column('locked_player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_email'), ['email'], unique=True)

    op.create_table('webhookevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replay_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creditledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creditledger_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creditledger_replay_id'), ['replay_id'], unique=False)

    op.create_table('replay',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('playlist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replay_account_id'), ['account_id'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replay_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('first_man', sa.Float(), nullable=False),
    sa.Column('second_man', sa.Float(), nullable=False),
    sa.Column('general', sa.Float(), nullable=False),
    sa.Column('licence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('main_leak', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('focus_chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_config_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metrics_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['replay_id'], ['replay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_replay_id'), ['replay_id'], unique=False)

    op.create_table('leaderboardentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('first_man', sa.Float(), nullable=False),
    sa.Column('second_man', sa.Float(), nullable=False),
    sa.Column('general', sa.Float(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaderboardentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboardentry_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboardentry_composite'), ['composite'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboardentry_season'), ['season'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboardentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboardentry_season'))
        batch_op.drop_index(batch_op.f('ix_leaderboardentry_composite'))
        batch_op.drop_index(batch_op.f('ix_leaderboardentry_account_id'))

    op.drop_table('leaderboardentry')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_replay_id'))

    op.drop_table('report')
    with op.batch_alter_table('replay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replay_account_id'))

    op.drop_table('replay')
    with op.batch_alter_table('creditledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creditledger_replay_id'))
        batch_op.drop_index(batch_op.f('ix_creditledger_account_id'))

    op.drop_table('creditledger')
    op.drop_table('webhookevent')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_email'))

    op.drop_table('account')
    # ### end Alembic commands ###
