"""account founding_number

Revision ID: afb2ad69a3ed
Revises: 4436ffaad795
Create Date: 2026-06-16 16:19:44.014308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afb2ad69a3ed'
down_revision: Union[str, Sequence[str], None] = '4436ffaad795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('founding_number', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_account_founding_number'), ['founding_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_founding_number'))
        batch_op.drop_column('founding_number')

    # ### end Alembic commands ###
