[package]
name = "remind_me_api"
version = "0.3.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Rusty-Mill/rusty_mill"

[package.metadata.rusty_mill]
layer = "apps"

[dependencies]
rusty_percent = { workspace = true }
rusty_oauth = { workspace = true }
remind_me_core.workspace = true

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
