//! `rusty_serde` - a small, dependency-free reimplementation of the ideas
//! behind [serde](https://serde.rs): a [`Serialize`]/[`Deserialize`] data
//! model that's independent of any wire format, plus a hand-written JSON
//! format built on top of it.
//!
//! ```
//! use rusty_serde::{Deserialize, Serialize};
//!
//! #[derive(Debug, PartialEq, Serialize, Deserialize)]
//! struct Point {
//!     x: i32,
//!     y: i32,
//! }
//!
//! let json = rusty_serde::json::to_string(&Point { x: 1, y: 2 }).unwrap();
//! assert_eq!(json, r#"{"x":1,"y":2}"#);
//!
//! let point: Point = rusty_serde::json::from_str(&json).unwrap();
//! assert_eq!(point, Point { x: 1, y: 2 });
//! ```

// Lets code generated by `#[derive(Serialize)]`/`#[derive(Deserialize)]`
// always refer to `::rusty_serde::...`, including from within this crate's
// own tests/doctests (which have no external `rusty_serde` dependency to
// resolve that path against otherwise).
#[cfg(feature = "derive")]
extern crate self as rusty_serde;

pub mod de;
pub mod error;
mod impls;
pub mod impossible;
pub mod json;
pub mod ser;

pub use crate::de::{Deserialize, Deserializer};
pub use crate::error::Error;
pub use crate::ser::{Serialize, Serializer};

#[cfg(feature = "derive")]
pub use rusty_serde_derive::{Deserialize, Serialize};
