#!/usr/bin/env python3
"""Generator for tests/data/tls12_signature_vectors.rs.

Handshake-signature vectors made by Python `cryptography` (OpenSSL), unrelated
to rusty_tls. Each carries the signing key's self-signed certificate (so a test
can take the SubjectPublicKeyInfo from a real parse), the message, and the
signature, for one TLS `SignatureScheme`.

The cross-curve ECDSA cases are the point: TLS 1.2 names only the hash in an
ECDSA scheme, so a P-384 key signed with the SHA-256 scheme is valid, and
OpenSSL 3.0 produces exactly that. TLS 1.3 forbids it.

    python3 tests/data/tls12_signature_vectors.py > tests/data/tls12_signature_vectors.rs
"""
import datetime

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, padding, rsa
from cryptography.x509.oid import NameOID

MESSAGE = bytes(range(64)) + b"client_random+server_random+ServerECDHParams"
NOW = datetime.datetime(2026, 1, 1)


def cert_der(key, sign_hash):
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "vector")])
    builder = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(1)
        .not_valid_before(NOW)
        .not_valid_after(NOW + datetime.timedelta(days=3650))
    )
    return builder.sign(key, sign_hash).public_bytes(serialization.Encoding.DER)


def vec(name, scheme, key, signature, sign_hash):
    return (name, scheme, cert_der(key, sign_hash), signature)


p256 = ec.generate_private_key(ec.SECP256R1())
p384 = ec.generate_private_key(ec.SECP384R1())
rsa_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
ed = ed25519.Ed25519PrivateKey.generate()

SHA256, SHA384, SHA512 = hashes.SHA256(), hashes.SHA384(), hashes.SHA512()
rows = [
    vec("ecdsa P-256 key, sha256 scheme", 0x0403, p256, p256.sign(MESSAGE, ec.ECDSA(SHA256)), SHA256),
    vec("ecdsa P-384 key, sha384 scheme", 0x0503, p384, p384.sign(MESSAGE, ec.ECDSA(SHA384)), SHA256),
    vec("ecdsa P-384 key, sha256 scheme (cross-curve)", 0x0403, p384, p384.sign(MESSAGE, ec.ECDSA(SHA256)), SHA256),
    vec("ecdsa P-256 key, sha384 scheme (cross-curve)", 0x0503, p256, p256.sign(MESSAGE, ec.ECDSA(SHA384)), SHA256),
    vec("rsa pkcs1 sha256", 0x0401, rsa_key, rsa_key.sign(MESSAGE, padding.PKCS1v15(), SHA256), SHA256),
    vec("rsa pkcs1 sha384", 0x0501, rsa_key, rsa_key.sign(MESSAGE, padding.PKCS1v15(), SHA384), SHA256),
    vec("rsa pkcs1 sha512", 0x0601, rsa_key, rsa_key.sign(MESSAGE, padding.PKCS1v15(), SHA512), SHA256),
]
for scheme, h in ((0x0804, SHA256), (0x0805, SHA384), (0x0806, SHA512)):
    sig = rsa_key.sign(MESSAGE, padding.PSS(mgf=padding.MGF1(h), salt_length=h.digest_size), h)
    rows.append(vec(f"rsa pss rsae {h.name}", scheme, rsa_key, sig, SHA256))
rows.append(vec("ed25519", 0x0807, ed, ed.sign(MESSAGE), None))

print("// @generated by tests/data/tls12_signature_vectors.py -- do not edit by hand.")
print()
print(f'const MESSAGE: &str = "{MESSAGE.hex()}";')
print()
print("const VECTORS: &[SigVector] = &[")
for name, scheme, cert, sig in rows:
    print(f'    SigVector {{ name: "{name}", scheme: 0x{scheme:04x}, certificate: "{cert.hex()}", signature: "{sig.hex()}" }},')
print("];")
