#!/usr/bin/env python3
"""Generator for tests/data/tls12_prf_vectors.rs.

Each vector is the output of OpenSSL's own TLS 1.2 PRF (`openssl kdf TLS1-PRF`),
an implementation unrelated to rusty_tls. OpenSSL takes label and seed as one
concatenated seed, exactly as RFC 5246 section 5 defines `PRF`.

    python3 tests/data/tls12_prf_vectors.py > tests/data/tls12_prf_vectors.rs
"""
import subprocess


def pat(n, start):
    return bytes((start + i * 11) & 0xFF for i in range(n))


def openssl_prf(digest, secret, label, seed, n):
    out = subprocess.run(
        ["openssl", "kdf", "-keylen", str(n), "-kdfopt", f"digest:{digest}",
         "-kdfopt", f"hexsecret:{secret.hex()}", "-kdfopt", f"hexseed:{(label + seed).hex()}", "TLS1-PRF"],
        check=True, capture_output=True, text=True).stdout
    return bytes.fromhex(out.strip().replace(":", ""))


CASES = []
for digest, hashname in (("SHA256", "Sha256"), ("SHA384", "Sha384")):
    # (secret length, label, seed length, output length)
    for sl, label, seedlen, outlen in (
        (1, b"", 1, 1),
        (16, b"test label", 13, 12),
        (32, b"master secret", 64, 48),
        (48, b"extended master secret", 32, 48),
        (48, b"extended master secret", 48, 48),
        (48, b"key expansion", 64, 40),
        (48, b"key expansion", 64, 72),
        (48, b"key expansion", 64, 88),
        (48, b"client finished", 32, 12),
        (48, b"server finished", 48, 12),
        (64, b"x" * 40, 100, 31),
        (100, b"block boundary", 7, 32),
        (100, b"block boundary", 7, 33),
        (100, b"block boundary", 7, 48),
        (100, b"block boundary", 7, 49),
        (100, b"block boundary", 7, 96),
        (100, b"block boundary", 7, 200),
    ):
        secret, seed = pat(sl, 1), pat(seedlen, 77)
        out = openssl_prf(digest, secret, label, seed, outlen)
        CASES.append((hashname, secret, label, seed, out))

print("// @generated by tests/data/tls12_prf_vectors.py -- do not edit by hand.")
print("// Outputs of OpenSSL's TLS1-PRF; see the generator.")
print()
print("const PRF_VECTORS: &[PrfVector] = &[")
for hashname, secret, label, seed, out in CASES:
    print(f'    PrfVector {{ hash: Hash::{hashname}, secret: "{secret.hex()}", label: "{label.hex()}", seed: "{seed.hex()}", out: "{out.hex()}" }},')
print("];")
