[package]
name = "ts-daemon"
description = "tailscaled-equivalent daemon binary"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ts-key.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "signal", "time"] }
ts-engine.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
