[package]
name = "ts-daemon"
description = "tailscaled-equivalent daemon binary"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ts-types.workspace = true
ts-key.workspace = true
ts-control.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true
