#!/usr/bin/env python3
"""Regenerates src/params.rs: curve parameters as little-endian u64 limbs.

Before emitting, checks each curve with exact integer arithmetic: the base
point is on the curve and has the stated order. Values are from SEC 2 / FIPS
186-4 (P-256, P-384) and RFC 7748 / RFC 8032 (Curve25519, Ed25519).
usage: gen_params.py > src/params.rs
"""

P256 = dict(
    p=0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF,
    n=0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551,
    b=0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B,
    gx=0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296,
    gy=0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5,
)
P384 = dict(
    p=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFF0000000000000000FFFFFFFF,
    n=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7634D81F4372DDF581A0DB248B0A77AECEC196ACCC52973,
    b=0xB3312FA7E23EE7E4988E056BE3F82D19181D9C6EFE8141120314088F5013875AC656398D8A2ED19D2A85C8EDD3EC2AEF,
    gx=0xAA87CA22BE8B05378EB1C71EF320AD746E1D3B628BA79B9859F741E082542A385502F25DBF55296C3A545E3872760AB7,
    gy=0x3617DE4A96262C6F5D9E98BF9292DC29F8F41DBD289A147CE9DA3113B5F0B8C00A60B1CE1D7E819D7A431D7C90EA0E5F,
)
P25519 = 2**255 - 19
ED_L = 2**252 + 27742317777372353535851937790883648493
ED_D = (-121665 * pow(121666, -1, P25519)) % P25519
ED_BY = 4 * pow(5, -1, P25519) % P25519


def ec_add(P, Q, p, a):
    if P is None:
        return Q
    if Q is None:
        return P
    if P[0] == Q[0] and (P[1] + Q[1]) % p == 0:
        return None
    if P == Q:
        lam = (3 * P[0] * P[0] + a) * pow(2 * P[1], -1, p) % p
    else:
        lam = (Q[1] - P[1]) * pow(Q[0] - P[0], -1, p) % p
    x = (lam * lam - P[0] - Q[0]) % p
    return (x, (lam * (P[0] - x) - P[1]) % p)


def ec_mul(k, P, p, a):
    R = None
    while k:
        if k & 1:
            R = ec_add(R, P, p, a)
        P = ec_add(P, P, p, a)
        k >>= 1
    return R


def check_weierstrass(c):
    p, a = c["p"], c["p"] - 3
    assert (c["gy"] ** 2 - (c["gx"] ** 3 + a * c["gx"] + c["b"])) % p == 0, "G not on curve"
    assert ec_mul(c["n"], (c["gx"], c["gy"]), p, a) is None, "wrong order"


def ed_base_x():
    p = P25519
    x2 = (ED_BY * ED_BY - 1) * pow(ED_D * ED_BY * ED_BY + 1, -1, p) % p
    x = pow(x2, (p + 3) // 8, p)
    if (x * x - x2) % p:
        x = x * pow(2, (p - 1) // 4, p) % p
    return p - x if x & 1 else x


def ed_add(P, Q):
    p = P25519
    (x1, y1), (x2, y2) = P, Q
    t = ED_D * x1 * x2 * y1 * y2 % p
    return ((x1 * y2 + x2 * y1) * pow(1 + t, -1, p) % p, (y1 * y2 + x1 * x2) * pow(1 - t, -1, p) % p)


def check_ed25519(bx):
    p = P25519
    assert (-bx * bx + ED_BY * ED_BY - 1 - ED_D * bx * bx * ED_BY * ED_BY) % p == 0, "B not on curve"
    R, B, k = (0, 1), (bx, ED_BY), ED_L
    while k:
        if k & 1:
            R = ed_add(R, B)
        B = ed_add(B, B)
        k >>= 1
    assert R == (0, 1), "B has wrong order"


def limbs(v, k):
    return ", ".join(f"0x{(v >> (64 * i)) & (2**64 - 1):016x}" for i in range(k))


def emit(name, v, k):
    print(f"pub(crate) const {name}: [u64; {k}] = [{limbs(v, k)}];")


check_weierstrass(P256)
check_weierstrass(P384)
BX = ed_base_x()
check_ed25519(BX)
print("// @generated by scripts/gen_params.py (curve checks run first). Do not edit.")
print("// Little-endian u64 limbs.")
for tag, c, k in (("P256", P256, 4), ("P384", P384, 6)):
    for key in ("p", "n", "b", "gx", "gy"):
        emit(f"{tag}_{key.upper()}", c[key], k)
emit("F25519_P", P25519, 4)
emit("ED_L", ED_L, 4)
emit("ED_D", ED_D, 4)
emit("ED_BX", BX, 4)
emit("ED_BY", ED_BY, 4)
emit("F25519_SQRT_M1", pow(2, (P25519 - 1) // 4, P25519), 4)
